### ISSUE TITLE
Enable building PDF for differential forms

### ISSUE THREAD

**Issue by ceciliachan1979** [ceciliachan1979/math#1]
Here is the issue related to supporting Chinese characters, there might be some updates.
https://github.com/xu-cheng/latex-action/issues/74

**Comment by kazutoiris** [comment]
Maybe you need to use `XeLaTeX` instead of `pdfLaTeX` to compile the Chinese tex file.

Good luck! 😃

**Comment by ceciliachan1979** [comment]
> Maybe you need to use `XeLaTeX` instead of `pdfLaTeX` to compile the Chinese tex file.
> 
> Good luck! 😃

Thank you for responding, yes, the flag `latexmk_use_xelatex: true` did the trick. The latest state of this repo is able to generate Chinese documents. I will probably do something on `https://github.com/xu-cheng/latex-action` to make this easier for people when I have time.
