### ISSUE TITLE
Elementary Number Theory Final Exam

### ISSUE THREAD

**Issue by E7-87-83** [ceciliachan1979/math#6]
_Elementary Number Theory Final Exam_
_Document: ./Exams/NumberTheory/Problems/Elementary_Number_Theory_Final_Exam__2021_Spring_.pdf_
_Date: June 2021_

Q1, Q2, Q6, Q7 okay

Q3, Q4, Q5 稍後睇...

**Comment by ceciliachan1979** [comment]
Thank you！呢份其實我大部份都可以用數值 verify。
